# Creating 3 servers

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# используем один и тот же ключ для всех машин
config.ssh.insert_key = false

config.vm.define "vagrant1" do |vagrant1|
   vagrant1.vm.box = "ubuntu/trusty64"
   vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
   vagrant1.vm.network "forwarded_port", guest: 80, host: 8443
   vagrant1.vm.network :private_network, ip: "192.168.100.100"
end

config.vm.define "vagrant2" do |vagrant2|
   vagrant2.vm.box = "ubuntu/trusty64"
   vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
   vagrant2.vm.network "forwarded_port", guest: 80, host: 8444
   vagrant2.vm.network :private_network, ip: "192.168.100.101"
end

config.vm.define "vagrant3" do |vagrant3|
   vagrant3.vm.box = "ubuntu/trusty64"
   vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
   vagrant3.vm.network "forwarded_port", guest: 80, host: 8445
   vagrant3.vm.network :private_network, ip: "192.168.100.102"
end

end
